# Numpy

- Numpy is a powerful linear algebra library for python.
- All the libraries in the PyData Ecosystem rely on numpy.
- Numpy is increbibly fast, as it has bindings to C libraries. Behind the scene the code has been optimized to run using C.
- Speed benefit is caused due to <u>Vectorization</u>. The vectorized version of the function takes a sequence of objects or NumPy arrays as input and evaluates the Python function over each element of the input sequence. Numpy Vectorization essentially functions like the python map() but with additional functionality – the NumPy <u>broadcasting</u> mechanism. Vectorization is achieved in Numpy using <u>Broadcasting</u>.
-<u>Vectorization</u> aims to do calculations by avoiding loops. it performs Mathematical functions for fast operations on entire arrays of data without having to write loops. 
- Some of the most important aspects of Numpy are 
    - Arrays
    - Vectors (Strictly 1-D Arrays)
    - Matrices (2-D Arrays) (a matrix can have one row and one column)
    - Broadcasting
    - Number generations

## NUMPY Array
- ndarray is an efficient multidimensional array providing fast array-oriented arithmetic operations and flexible broadcasting abilities.
- Numpy array are fast, felxible container for large datasets in python
- Numpy arrays essentially come in two flavors: vectors and matrices
    - Vectors are strictly 1-dimensional (1D) arrays
    - matrices are multi-deminsional list (2D, 3D) of arrays

## Advantages of using NUMPY arrays
- Memory Efficiency of Numpy Array vs list
- Easily expands to N-dimensional objects
- Speed calculations of Numpy array
- Broadcasting operatrions and Functions

## Differences between NUMPY Arrays and LIST
- Numpy arrays have a fixed size at creation, unlike python lists which can grow dynamically. Changing the size of array in numpy will create a new array and delete the old array.
- The elements in a numpy array are all required to be of the same data type and thus will be of the same size in memory
- Numpy arrays are fascilitated by advanced mathematical operations. Typically such operations are executed more efficiently and with less code than is possible using python build in sequences.  
- Numpy supports vectorized operations like elementwise addition and multiplication.

### Importing NUMPY

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]
my_array = np.array([1,2,3])

In [3]:
print(type(my_list))
print(type(my_array))

<class 'list'>
<class 'numpy.ndarray'>


#### Numpy based algorithms are generally 10 to 100 times faster than their pure Python counterparts and use significantly less memory

In [4]:
my_array = np.arange(1000000)
my_list = list(range(1000000))

In [5]:
%time for _ in range(0,10): my_array = my_array * 2

CPU times: user 1.12 s, sys: 2.6 s, total: 3.72 s
Wall time: 4.43 s


In [6]:
%time for _ in range(0,10): [x*2 for x in my_list]

CPU times: user 48 s, sys: 27.9 s, total: 1min 15s
Wall time: 1min 37s


## Creating NUMPY arrays from Objects


## Built-in methods to create arrays
- arange()
- linspace()
- zeros()
- ones()
- eye()
- randint()
- randn()
- rand()
- empty()

### From Python List we can generate arrays

#### np.array()
- takes python list as input and returns an array

In [7]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [8]:
np.array(my_list)

array([1, 2, 3])

In [9]:
my_list_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_list_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(my_list_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

In [12]:
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 3, 3), 3, dtype('int64'), 18, numpy.ndarray)

### From Built in Methods we can generate arrays

#### arange
- returns evenly spaced values within a given interval
- arange is an array-valued version of the built-in Python range function

In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [15]:
np.arange(0,11,2).dtype

dtype('int64')

#### zeros and ones
- return arrays of zeros and ones of the given dimension

In [16]:
np.zeros(3)

array([0., 0., 0.])

In [17]:
np.zeros(3).dtype

dtype('float64')

In [18]:
np.zeros(3).astype(int)

array([0, 0, 0])

In [19]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
np.ones((5,5)).astype(int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### empty
- np.empty may return an array of all zeros. In some cases, it may return uninitialized 'garbage' values

In [22]:
np.empty((1,2))

array([[2.05833592e-312, 2.33419537e-312]])

#### linspace
- return evenly spaced numbers over a specified interval

In [23]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [24]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [25]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

#### eye
- Create an identity matrix

In [26]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### From Built-in Functions we can generate random arrays
- from np.random we can use various functions to generate random arrays
- The Numpy.random module supplements the built in python random with functions for efficiently generating whole arrays of sample values from many kinds of probability distributions.
    - rand()
    - randn()
    - randint()
    - binomial()
    - normal()

#### rand
 - creates an array of the given shape and populates it with radnom samples from a uniform distribution over (0,1) interval.

In [27]:
np.random.rand(2)

array([0.73147687, 0.43970139])

In [28]:
np.random.rand(5,5)

array([[0.74140349, 0.00530281, 0.4474363 , 0.86253468, 0.87161216],
       [0.02795269, 0.97149593, 0.12044199, 0.56326902, 0.85888322],
       [0.82553987, 0.98087048, 0.84070821, 0.91385262, 0.2001669 ],
       [0.27170671, 0.62050156, 0.28839297, 0.77655273, 0.52547899],
       [0.99002437, 0.04981725, 0.19880164, 0.71800547, 0.94362949]])

#### randn
- returns a sample from the 'standard normal' distribution (sd = 1)
- unlike rand which is uniform, values closer to zero are more likely to appear

In [29]:
np.random.randn(2)

array([1.7130154 , 0.60586345])

In [30]:
np.random.randn(5,5)

array([[ 0.5167903 ,  0.9450621 ,  0.96777329, -0.50597976, -0.31124759],
       [-0.37621588, -0.42955588, -1.98684611, -1.51577983,  0.61940252],
       [-0.54939908,  0.22644136, -0.7489763 , -0.41435072,  1.54155708],
       [ 0.51224602, -0.3376486 ,  1.01219029,  0.91142745,  1.5603642 ],
       [ 1.09201639,  0.68164914,  0.98726359, -0.61377205, -1.11727682]])

#### randint
- returns random integers from low(inclusive) to high(exclusive)

In [31]:
np.random.randint(1,100)

31

In [32]:
np.random.randint(1,100,10)

array([70, 66, 29, 86, 17,  7, 92, 44, 27, 87])

In [33]:
np.random.randint(1,100,(2,2))

array([[ 3, 43],
       [18, 80]])

#### binomial
- draw samples from a binomial distribution

In [34]:
np.random.binomial(13,0.8)

10

## Array Attributes and Methods
- reshape()
- shape
- max()
- min()
- argmax()
- argmin()

In [35]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
ranarr

array([44,  7,  6, 35,  2, 29, 21, 19, 30, 11])

#### reshape
- returns an array containing the same data with a new shape

In [38]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### max, min, argmax, argmin
- useful method for finding max and min values or to find their index locations using argmin and argmax

In [39]:
ranarr

array([44,  7,  6, 35,  2, 29, 21, 19, 30, 11])

In [40]:
ranarr.min()

2

In [41]:
ranarr.max()

44

In [42]:
ranarr.argmax()

0

In [43]:
ranarr.argmin()

4

#### Shape
- shape is an attribute that arrays have
- every array has a shape, a tuple indicating the size of each dimension

In [44]:
arr.shape

(25,)

In [45]:
ranarr.shape

(10,)

In [46]:
arr.reshape(5,5).shape

(5, 5)

#### dtype
- ndarray is a container for homogeneous data i.e. all the elements must be the same data type
- grabs the data type of the object
- is a special object containing the information (or metadata, data about data) the ndarray needs to interpret a chunk of memory as a particular type of data

In [47]:
arr.dtype

dtype('int64')

In [48]:
arr2 = np.array([1.1,2.3,4.6])
arr2.dtype

dtype('float64')

In [49]:
arr = np.array([1,2,3,4,5])

In [50]:
arr.dtype

dtype('int64')

In [51]:
float_arr = arr.astype(np.float64)

In [52]:
float_arr.dtype

dtype('float64')

In [53]:
numeric_strings = np.array(['1.25','-9.6','42'])

In [54]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

# Numpy Indexing and Selection

### Indexing a 1-D array

In [55]:
arr = np.arange(0,11)

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
arr[8]

8

In [58]:
arr[1:5]

array([1, 2, 3, 4])

In [59]:
arr[5]

5

In [60]:
arr[5:8]

array([5, 6, 7])

In [61]:
arr_slice = arr[5:8]
arr_slice

array([5, 6, 7])

In [62]:
arr_slice[1] = 12345
arr_slice

array([    5, 12345,     7])

In [63]:
arr

array([    0,     1,     2,     3,     4,     5, 12345,     7,     8,
           9,    10])

## Broadcasting
- the diference between python list and Numpy array is the ability to broadcast
- Broadcasting is a feature of Numpy which performs an operation across multiple dimensions of data without replicating the data.
- if the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its left side.

In [64]:
arr[0:5] = 100

In [65]:
arr

array([  100,   100,   100,   100,   100,     5, 12345,     7,     8,
           9,    10])

In [66]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [68]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

### Array slices are views on the original array. This means that the data is not copied and any modification to the view will be reflected in the source array.

In [69]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [70]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
old_values = arr3d[0].copy()

In [72]:
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [73]:
old_values

array([[1, 2, 3],
       [4, 5, 6]])

## Indexing a 2-D array

In [74]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [75]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [76]:
arr_2d[1] 

array([20, 25, 30])

In [77]:
arr_2d[1][1]

25

In [78]:
arr_2d[1][0]

20

In [79]:
arr_2d[2,:]

array([35, 40, 45])

In [80]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [81]:
arr_2d[0,1:3]

array([10, 15])

In [82]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [83]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [84]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

## Conditional Selection
- Like arithematic operation conditions with arrays are also vectorized

In [85]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [87]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [88]:
x = 2
arr[arr > x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data = np.random.randn(7,4)
print(names)
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[ 1.30149436 -0.66457307  1.30239559 -1.19807879]
 [ 0.79478188  1.50871784 -1.75777255  1.25525034]
 [ 0.07109702  0.5356146  -0.18225093  0.43093209]
 [ 2.48372634 -0.58673816  0.91774648  1.50854626]
 [-0.39928866  0.11472396  0.27563847  1.19803768]
 [ 1.21908192 -1.00481127  1.06545809 -1.04011789]
 [-1.40472181  2.06775154 -0.55264045 -2.25435338]]


In [90]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [91]:
names[names == 'Bob']

array(['Bob', 'Bob'], dtype='<U4')

In [92]:
data[names == 'Bob']

array([[ 1.30149436, -0.66457307,  1.30239559, -1.19807879],
       [ 2.48372634, -0.58673816,  0.91774648,  1.50854626]])

In [93]:
data[names == 'Bob',2:]

array([[ 1.30239559, -1.19807879],
       [ 0.91774648,  1.50854626]])

In [94]:
names!='Bob'
data[~(names == 'Bob')]

array([[ 0.79478188,  1.50871784, -1.75777255,  1.25525034],
       [ 0.07109702,  0.5356146 , -0.18225093,  0.43093209],
       [-0.39928866,  0.11472396,  0.27563847,  1.19803768],
       [ 1.21908192, -1.00481127,  1.06545809, -1.04011789],
       [-1.40472181,  2.06775154, -0.55264045, -2.25435338]])

In [95]:
data[data<0]=0

In [96]:
data

array([[1.30149436, 0.        , 1.30239559, 0.        ],
       [0.79478188, 1.50871784, 0.        , 1.25525034],
       [0.07109702, 0.5356146 , 0.        , 0.43093209],
       [2.48372634, 0.        , 0.91774648, 1.50854626],
       [0.        , 0.11472396, 0.27563847, 1.19803768],
       [1.21908192, 0.        , 1.06545809, 0.        ],
       [0.        , 2.06775154, 0.        , 0.        ]])

# Numpy Operations
- arrays are important because they enable you to express batch operations on data without writing any for loop. Numpy users call this vectorizaton.
- Numpy arrays are facilitated by Advanced Mathematical operations. Typically such operations are executed more efficiently with less code as compared to Built-in python functions

In [97]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [99]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [100]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [101]:
# will not raise an error but just a warning because 1/0 is infinity
1/arr

<ipython-input-101-aaf11e3ac3e2>:2: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

## Universal Array Functions 
- Numpy has many universal array functions which are just mathematical operations that can be applied across the array, element by element fashion, supporting array broadcasting, type casting and several other standard features
- Universal Functions is a vectorized wrapper for a function that takes a fixed number of specific inputs and produces a fixed number of specific outputs
    - abs()
    - sqrt()
    - square()
    - exp()
    - log()
    - sin(), cos(), tan()
    - ceil()
    - floor()
    - isnan()
    - add()
    - subtract()
    - multiply()
    - divide()
    - power()
    - greater(), greater_equal()
    - less()
    - equal(), not_equal()

In [102]:
array_neg = np.random.randn(5,5)
array_neg

array([[-1.33924062, -0.26339617,  0.72285974, -0.16612151,  1.3795371 ],
       [ 1.55929096,  0.66069537, -0.60025229,  0.11333407, -0.83386544],
       [ 0.6770549 ,  0.32881587, -1.9538447 , -1.20277441, -1.32547067],
       [ 0.42523612,  0.04599099,  0.07014406,  0.89566851,  0.74217251],
       [ 0.43536145,  1.49351382, -1.38429292,  1.46934307,  0.90060792]])

In [103]:
np.abs(array_neg)

array([[1.33924062, 0.26339617, 0.72285974, 0.16612151, 1.3795371 ],
       [1.55929096, 0.66069537, 0.60025229, 0.11333407, 0.83386544],
       [0.6770549 , 0.32881587, 1.9538447 , 1.20277441, 1.32547067],
       [0.42523612, 0.04599099, 0.07014406, 0.89566851, 0.74217251],
       [0.43536145, 1.49351382, 1.38429292, 1.46934307, 0.90060792]])

In [104]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [105]:
arr_sq = np.arange(10)
arr_sq

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
np.square(arr_sq)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [107]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [108]:
np.log(arr)

<ipython-input-108-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [109]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [110]:
np.ceil(np.abs(array_neg))

array([[2., 1., 1., 1., 2.],
       [2., 1., 1., 1., 1.],
       [1., 1., 2., 2., 2.],
       [1., 1., 1., 1., 1.],
       [1., 2., 2., 2., 1.]])

In [111]:
np.floor(np.abs(array_neg))

array([[1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.]])

In [112]:
arr = np.arange(0,25).reshape(5,5)

In [113]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [114]:
np.add(arr,np.abs(array_neg))

array([[ 1.33924062,  1.26339617,  2.72285974,  3.16612151,  5.3795371 ],
       [ 6.55929096,  6.66069537,  7.60025229,  8.11333407,  9.83386544],
       [10.6770549 , 11.32881587, 13.9538447 , 14.20277441, 15.32547067],
       [15.42523612, 16.04599099, 17.07014406, 18.89566851, 19.74217251],
       [20.43536145, 22.49351382, 23.38429292, 24.46934307, 24.90060792]])

## Summary Statistics on Arrays

In [115]:
arr 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [116]:
arr.sum()

300

In [117]:
arr.sum(axis=1)

array([ 10,  35,  60,  85, 110])

In [118]:
arr.sum(axis = 0)

array([50, 55, 60, 65, 70])

In [119]:
arr.mean()

12.0

In [120]:
arr.max()

24

In [121]:
arr.min()

0

In [122]:
arr.var()

52.0

In [123]:
arr.std()

7.211102550927978

## Fancy Indexing
- fancy indexing is a term adopted by Numpy to describe indexing using integer arrays.

In [124]:
arr = np.empty((8,4))
arr

array([[0.00000000e+000, 1.48219694e-323, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 5.02034658e+175, 2.88024405e+180,
        3.44024018e+179],
       [3.69846728e-057, 2.61142081e-057, 5.93988848e-038,
        3.59751658e+252],
       [8.93185432e+271, 7.33723594e+223, 1.47763641e+248,
        1.16096346e-028],
       [5.03396546e+223, 3.97062394e+246, 1.16318408e-028,
        1.26757382e-071],
       [1.11640482e-046, 2.61989618e+180, 1.58767276e-047,
        3.98450697e+252],
       [6.74640243e-067, 4.57753266e-071, 3.45853676e-086,
        3.35760521e-143],
       [4.82337433e+228, 6.14415221e-144, 1.58718589e-319,
        0.00000000e+000]])

In [125]:
for _ in range(8):
    arr[_] = _
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [126]:
arr[[4,5]]

array([[4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [127]:
arr[[4,5,6,7]]

array([[4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

## Array-Oriented Programming with Arrays
- The practice of replacing explicit loops with array expressions is commonly referred to as vectorization. Vectorized array problems will often be one or two orders of magnitude faster than their pure Python equivalents.

In [128]:
x = np.arange(0,6)
y = np.arange(0,5)
print(x)
print(y)

[0 1 2 3 4 5]
[0 1 2 3 4]


In [129]:
xs, ys = np.meshgrid(x, y)

In [130]:
xs

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

In [131]:
ys

array([[0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4]])

In [132]:
z = np.sqrt(xs**2 + ys**2)

In [133]:
z

array([[0.        , 1.        , 2.        , 3.        , 4.        ,
        5.        ],
       [1.        , 1.41421356, 2.23606798, 3.16227766, 4.12310563,
        5.09901951],
       [2.        , 2.23606798, 2.82842712, 3.60555128, 4.47213595,
        5.38516481],
       [3.        , 3.16227766, 3.60555128, 4.24264069, 5.        ,
        5.83095189],
       [4.        , 4.12310563, 4.47213595, 5.        , 5.65685425,
        6.40312424]])

## Where Conditional Logic
- numpy.where functions is a vectorized version of the ternary expressions

In [134]:
xarr = np.array([1.1,1.2,1.3,1.4,1.5])
yarr = np.array([2.1,2.2,2.3,2.4,2.5])
cond = np.array([True, False, True, True, False])

In [135]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [136]:
arr = np.random.randn(2,2)
arr

array([[ 1.64144589,  0.88741467],
       [-0.59665522, -1.09888796]])

In [137]:
np.where(arr > 0, 2, arr)

array([[ 2.        ,  2.        ],
       [-0.59665522, -1.09888796]])